プレイヤーにステートを追加
tricore-as16/ZombiFPS pull request #10
Opened 2024-08-02 03:27 UTC by tricore-as16

プレイヤーのステートマシンのような実装を行いました。まだ、ステートの中身はアニメーションしか追加しておらず、すべてIdleのアニメーションを再生するようにしています。走るアニメーションを追加したかったのですが、銃と動きを同期させる必要がありコード量が増えると感じたため、ステート切り替えができたこの段階でプルリクエスト送信しました。

・キー入力に応じてプレイヤーのステートを切り替えるように変更しました
・ステートに応じてアニメーションを変更するようにしました
・ステートに応じてプレイヤーの移動速度を変更するようにしました

2024-08-02 08:03 UTC, tricore-as07 requested changes

2024-08-02 08:03 UTC, tr-k-orimoto commented on GunBase.cpp
> +/// <param name="cameraForwardVector"></param>
[MUST]
記入漏れ

2024-08-02 08:03 UTC, tr-k-orimoto commented on GunBase.h
> +    // 銃の位置調整
[MUST]
コメントの形式が揃えられていないのと、
銃の位置調整もUpdateGunPositionのようにして回転の更新などと統一したほうがわかりやすい気がしました。

2024-08-02 08:03 UTC, tr-k-orimoto commented on Player.cpp
> +    else if((state == State::Idle || state == State::Walk || state == State::Run) && CheckHitKey(KEY_INPUT_LSHIFT))
[MUST]
ここで使っている

> state == State::Idle || state == State::Walk || state == State::Run

は下でも使われているので、if文に入る前に名前を付けてあげて判定を1回にしてあげると
処理も軽くなり、この条件が変更されたときも1か所を修正すればいいので変更漏れでの不具合が無くなります。

2024-08-02 08:03 UTC, tricore-as07 commented on PlayerStateBase.h
> +    PlayerStateBase(int& playerModelHandle, AnimationData previousStateData);
[Q]
モデルハンドルを参照渡しで持ってきてる理由って何かありますか？

2024-08-02 13:37 UTC, tricore-as16 commented on GunBase.cpp
> +/// <param name="cameraForwardVector"></param>
すいません。追加しました。

2024-08-02 13:52 UTC, tricore-as16 commented on GunBase.h
> +    // 銃の位置調整
承知しました。UpdateGunPosition関数にまとめました。

2024-08-03 04:35 UTC, tricore-as16 commented on Player.cpp
> +    else if((state == State::Idle || state == State::Walk || state == State::Run) && CheckHitKey(KEY_INPUT_LSHIFT))
ありがとうございます。気づきませんでした。変数名がよいのが思いつかずisIdleWalkRunにしました。

2024-08-03 04:37 UTC, tricore-as16 commented on PlayerStateBase.h
> +    PlayerStateBase(int& playerModelHandle, AnimationData previousStateData);
すいません。モデルハンドルが固有番号なので別に参照渡しである必要はありませんでした。値渡しに変更しました。

2024-08-05 02:25 UTC, tricore-as07 commented on GunBase.cpp
> +﻿#include "GunBase.h"\\\//////////////////////////////////////////////////////////////////////////////////\
[Q]
これはどういう意図の記述でしょうか?

2024-08-05 02:36 UTC, tricore-as16 commented on GunBase.cpp
> +﻿#include "GunBase.h"\\\//////////////////////////////////////////////////////////////////////////////////\
申し訳ありません。不要なため削除しました。

2024-08-05 05:37 UTC, tricore-as07 approved these changes
LGTM

2024-08-05 05:37 UTC, merged