プレイヤーに走るアニメーションを追加
tricore-as16/ZombiFPS pull request #11
Opened 2024-08-05 01:38 UTC by tricore-as16

プレイヤーが走り状態のとき、プレイヤーと銃を下に下げるように変更しました。

2024-08-06 01:59 UTC, tricore-as03 requested changes

2024-08-06 01:59 UTC, tricore-as03 commented on Player.cpp
> +        }
[MUST]
ここ走りのステートのクラス内でできませんか？

2024-08-06 01:59 UTC, tricore-as03 commented on AssaultRifle.cpp
> +    //UpdateAngle(cameraVector, cameraPitch);
[MUST]
消してください。

2024-08-06 01:59 UTC, tricore-as03 commented on GunBase.cpp
> +    }
[MUST]
ここも走るステートのクラスに移動できませんか？

2024-08-06 02:03 UTC, tricore-as16 commented on AssaultRifle.cpp
> +    //UpdateAngle(cameraVector, cameraPitch);
すいません。削除しました。

2024-08-06 02:13 UTC, tricore-as16 commented on Player.cpp
> +        }
すいません。すぐにステートクラス内の処理に移動させるやり方が思いつかないのですがどうすればよいでしょうか？

また、この後に「銃を撃つ」と、「銃をリロードする」２つのプルリクエスト内でも処理をステートクラスに分けていないためまとめて全体で行いたいと思っているのですが大丈夫でしょうか。

2024-08-06 02:15 UTC, tricore-as16 commented on GunBase.cpp
> +    }
現状の段階で、銃を撃つステートと、銃をリロードするステートでも分けたクラス内で処理を行っていないのでステート全体でまとめて行いたいと思っているのですが大丈夫でしょうか？

2024-08-06 06:48 UTC, tricore-as03 requested changes

2024-08-06 06:48 UTC, tricore-as03 commented on Player.cpp
> +        }
> すいません。すぐにステートクラス内の処理に移動させるやり方が思いつかないのですがどうすればよいでしょうか？

該当部分の処理を関数化してしまって、「走る」ステートの中で呼ぶ形でよいかと。
`runAnimationLerpFactor`と`RunAnimationFactorSpeed`も走り関係の変数なので、走るステートが持つ形でよいかと。

>また、この後に「銃を撃つ」と、「銃をリロードする」２つのプルリクエスト内でも処理をステートクラスに分けていないためまとめて全体で行いたいと思っているのですが大丈夫でしょうか。

設計上そうせざるを得ないのであれば仕方ないのですが、まとめた結果変更差分が増えすぎるのもよくないので、できればこのプルリクで修正してほしいですね。
「銃を撃つ」と「銃をリロードする」は今回の「走る」とは別なので、まとめなくても対応できそうですがどうでしょう？

2024-08-06 06:48 UTC, tricore-as03 commented on GunBase.cpp
> +    }
https://github.com/tricore-as16/ZombiFPS/pull/11#discussion_r1704993850
これも同様に

2024-08-06 06:57 UTC, tricore-as16 commented
コメント内容承知しました。走るアニメーション部分を関数化して、ステートで呼び出すようにしてみます。

2024-08-07 03:03 UTC, tricore-as16 commented on GunBase.cpp
> +    }
ステートベース側でステートごとのオフセット量を返すように変更しました。

2024-08-07 03:03 UTC, tricore-as16 commented on Player.cpp
> +        }
ステートベース側でステートごとのオフセット量を返すように変更しました。

2024-08-08 09:29 UTC, tricore-as03 approved these changes
LGTM

2024-08-09 01:09 UTC, merged