エネミーの線形探索を実装しました。
tricore-as16/ZombiFPS pull request #15
Opened 2024-08-20 06:14 UTC by tricore-as16

・線形探索クラスで、部屋の情報を定義、エネミーがプレイヤー部屋への最短経路を検索
・エネミーは部屋の中心座標を経由してプレイヤーにたどりつくように実装

2024-08-20 09:30 UTC, tricore-as03 requested changes

2024-08-20 09:30 UTC, tricore-as03 commented on EnemyGroup.cpp
> +VECTOR EnemyGroup::UpdateEnemyPathfinding(VECTOR playerPosition,Enemy& enemy, Stage& stage)
[MUST]
この関数の役割は敵の目標位置を更新することなので、`UpdateEnemyTargetPosition`がよいかと。

2024-08-20 09:30 UTC, tricore-as03 commented on Pathfinding.cpp
> +    initRoomData[East4]     = { East4,     VGet(  50.0f,  4.5f, -35.0f),      10,        28,       imageDataManager->GetImageHandle(ImageDataManager::East4ImageData) };
[IMO]
```
class RoomInitializeData
{
    RoomNumber roomNumber;
    VECTOR centerPosition;
    float width;
    float depth;
    int imageHandle;
}
```
こんな感じの初期化専用のデータをまとめるクラスを作って、それを部屋の数だけリストで持って、`initRoomData`にはforでセットしたいですね。
すぐ出来そうであればやってほしいですが、強制ではないです。

2024-08-20 13:53 UTC, tricore-as16 commented on EnemyGroup.cpp
> +VECTOR EnemyGroup::UpdateEnemyPathfinding(VECTOR playerPosition,Enemy& enemy, Stage& stage)
承知いたしました。
変更いたします。

2024-08-20 13:56 UTC, tricore-as16 commented on Pathfinding.cpp
> +    initRoomData[East4]     = { East4,     VGet(  50.0f,  4.5f, -35.0f),      10,        28,       imageDataManager->GetImageHandle(ImageDataManager::East4ImageData) };
ありがとうございます。
のちのブランチで定数化している個所があり、そのブランチで修正した方が効率が良いと感じるのと、新しくクラスファイルを作成するとヴィジュアルスタジオのファイル保存が壊れてばらばらになる不具合がよく発生し、原因もわかっていないため見送らせていただいてもよろしいでしょうか？
申し訳ございません。

2024-08-21 03:35 UTC, tricore-as03 commented on Pathfinding.cpp
> +    initRoomData[East4]     = { East4,     VGet(  50.0f,  4.5f, -35.0f),      10,        28,       imageDataManager->GetImageHandle(ImageDataManager::East4ImageData) };
了解です。状況把握です。

2024-08-21 03:36 UTC, tricore-as03 approved these changes
LGTM

2024-08-21 05:24 UTC, merged