エネミーのオブジェクトプール実装、ウェーブ管理実装
tricore-as16/ZombiFPS pull request #16
Opened 2024-08-20 06:18 UTC by tricore-as16

・エネミーをオブジェクトプールで実装するように変更しました
・エネミーをウェーブ方式で出現させるようにしました

※まだエネミーのスポーン場所は１か所で、今後３か所にする予定です。
　ウェーブが上昇するとエネミーのHPが上がるようにする予定です

2024-08-21 08:02 UTC, tricore-as03 requested changes

2024-08-21 08:02 UTC, tr-t-mitsumaru commented on EnemyWaveController.cpp
> +void EnemyWaveController::Update(int activeEnemyNumber)
[MUST]
`activeEnemyCount`が良いかと。
`Number`だとアクティブになっている敵の識別番号なのかと勘違いしそうなので。
識別番号とかの単純な値は`Number`、変動する可能性のある何らかの数を表すときは`Count`というような使い分けをするとよかいと思います。

2024-08-21 08:02 UTC, tricore-as03 commented on EnemyWaveController.cpp
> +    if (GetNowCount() - lastEnemySpawnTime >= EnemySpawnResponseTime * 1000)
[IMO]
読めないことはないですが、ちょっとif文のネストが深すぎますね。
```
bool isSpawnTime = GetNowCount() - lastEnemySpawnTime >= EnemySpawnResponseTime * 1000;
bool isLimitSpawnCountInWave = (currentWaveState * EnemySpawnRate) < currentWaveSpawnCount;
bool isLimitSpawnCount = activeEnemyNumber > EnemySpawnLimit;
bool canSpawnEnemy = isSpawnTime && !isLimitSpawnCountInWave && !isLimitSpawnCount && !enemySpawnFlag;
if (canSpawnEnemy)
{
    
}
```
こんな感じでローカル変数で条件に名前を付けてあげると、読みやすくなります。

2024-08-22 00:55 UTC, tricore-as16 commented on EnemyWaveController.cpp
> +void EnemyWaveController::Update(int activeEnemyNumber)
承知しました。
確かにnumberだと識別番号ととらえられて今いかねない名前でした。
activeEnemyCountに変更しました。

2024-08-22 01:04 UTC, tricore-as16 commented on EnemyWaveController.cpp
> +    if (GetNowCount() - lastEnemySpawnTime >= EnemySpawnResponseTime * 1000)
アドバイスありがとうございます。
すいません。ネストが深すぎました。これから条件文が複数ある場合はこの方法を使ってみようと思います。
修正しました。

2024-08-22 01:53 UTC, tricore-as03 approved these changes
LGTM

2024-08-22 02:13 UTC, merged