エネミーのOnHit関数、ウェーブステート切り替えを実装
tricore-as16/ZombiFPS pull request #17
Opened 2024-08-20 06:21 UTC by tricore-as16

・エネミーのOnHit関数を実装
・エネミーの死亡アニメーションを追加
・そのウェーブで出現するエネミーをすべて倒すと、ウェーブが進行するように修正

※エネミーの攻撃はまだ実装途中でまだ正常に機能しません

2024-08-21 08:20 UTC, tr-t-mitsumaru requested changes

2024-08-21 08:20 UTC, tr-t-mitsumaru commented on Enemy.cpp
> +        //MV1SetPosition(modelHandle, position);
[MUST]
残している理由があればコメントで書いてください。

2024-08-22 01:51 UTC, tricore-as16 commented on Enemy.cpp
> +        //MV1SetPosition(modelHandle, position);
すみません。不要なので削除します。

2024-08-22 02:10 UTC, tricore-as03 approved these changes
LGTM

2024-08-22 02:20 UTC, merged