銃の総弾数、リロード時に総弾数を回復する実装を追加
tricore-as16/ZombiFPS pull request #18
Opened 2024-08-20 06:24 UTC by tricore-as16

・プレイヤーの装備中の銃に総弾数を追加
・リロード時に総弾数を回復するように修正
・弾丸が当たった際にお金を獲得を追加

2024-08-21 10:34 UTC, tricore-as03 requested changes

2024-08-21 10:34 UTC, tr-t-mitsumaru commented on Bullet.h
> +    static constexpr int    ActiveFrameCount        = 1;                    // 弾丸がアクティブであるフレーム数
[Q]
この変数を用意した理由はなんでしょうか？
弾は敵や障害物に当たったら消えると思うので、必要ないと思うのですが。

2024-08-21 10:34 UTC, tricore-as03 commented on GunBase.h
> +    static constexpr float  HipUpPositionAnglePitch     = 30.0f * DX_PI_F / 180.0f;     // 垂直回転用：腰だめの位置に調整するために回転させる水平方向からの角度(ラジアン)
[MUST]
コメントや変数の意味が良く分からないんですが、詳細を教えていただけますでしょうか？

2024-08-22 02:31 UTC, tricore-as16 commented on Bullet.h
> +    static constexpr int    ActiveFrameCount        = 1;                    // 弾丸がアクティブであるフレーム数
不要なため削除しました。

2024-08-22 02:36 UTC, tricore-as16 commented on Bullet.h
> +    static constexpr int    ActiveFrameCount        = 1;                    // 弾丸がアクティブであるフレーム数
弾丸がエネミーに当たった時にプレイヤーの所持金を増やしたかったため追加しました。
処理順番が、
プレイヤー→銃→弾→当たり判定→OnHit
、でこの変数がないとOnHitの後でたまに保存されたポイントをプレイヤーに送ることが出来なかったため、弾を次のフレームまでアクティブにさせるために実装しました。

2024-08-22 02:51 UTC, tricore-as16 commented on GunBase.h
> +    static constexpr float  HipUpPositionAnglePitch     = 30.0f * DX_PI_F / 180.0f;     // 垂直回転用：腰だめの位置に調整するために回転させる水平方向からの角度(ラジアン)
銃のモデル座標をカメラの座標と同じにすると銃が、FPSゲームでいうアイアンサイトを覗き込んだような状態になり、FPSゲームの腰だめの位置（サイトを覗かずの腰の位置に銃を持つ）に角度を調整するために角度調整する値の定数値にしていました。
　「腰だめ」が英語でわからなかったため検索した結果、腰だめ→HipUpPositionというのが出てきたためそれを採用させていただきました。

HipUpPositionAngleY   →銃が３次元空間上のY軸を起点に回転する値です。（ライザップのように回転する感じです）

HipUpPositionAnglePitch  →銃が３次元空間上のX軸を起点に回転する値です。（お辞儀するように回転します）

命名が分かりずらく申し訳ございませんでした。


この変数が適用されない場合の画像となります。
![スクリーンショット 2024-08-22 114441](https://github.com/user-attachments/assets/c04453f8-1d99-456c-bdcc-9fb0cc6af536)

2024-08-22 03:29 UTC, tricore-as16 commented on GunBase.h
> +    static constexpr float  HipUpPositionAnglePitch     = 30.0f * DX_PI_F / 180.0f;     // 垂直回転用：腰だめの位置に調整するために回転させる水平方向からの角度(ラジアン)
Fixme
Enemyに定数で５０ポイント加算、１０加算
EnemyにPlayerの50ポイント加算関数、１０ポイント加算関数の関数ポインタ変数を持つ

Player側は50ポイント加算関数、１０ポイント加算関数
を作成し、エネミーにその関数を渡す

2024-08-22 06:17 UTC, tricore-as03 approved these changes
LGTM

2024-08-22 07:18 UTC, merged