ゲームシーンにUIを追加
tricore-as16/ZombiFPS pull request #20
Opened 2024-08-20 06:28 UTC by tricore-as16

・予備弾薬数
・ウェーブ数
・ビデオ風の画面フィルター
・ドアのコスト
などをUIとして表示追加を行いました。

2024-08-26 05:47 UTC, tricore-as03 requested changes

2024-08-26 05:47 UTC, tricore-as03 commented on CollisionData.h
> +    float       objectHP;               // オブジェクトの体力
[IMO]
CollisionDataはあくまで当たり判定に必要な情報をまとめるクラスなので、それに関係ないデータは含めるべきではないですね。
HPがあるのはプレイヤーと敵だけだと思いますが、それぞれのクラスに変数を設ける形で対応できませんか？

2024-08-28 02:31 UTC, tricore-as16 commented on CollisionData.h
> +    float       objectHP;               // オブジェクトの体力
弾丸がエネミーに当たった時に、この弾丸でエネミーのHPがゼロになれば追加でポイントを与えるという仕様があり、
弾丸がエネミーのHPを確認できないと現在の接触時にHPがゼロになるかが分からなかったため追加させていただきました。

2024-09-02 04:31 UTC, tricore-as03 approved these changes
LGTM

2024-09-02 04:52 UTC, merged