サウンドを追加
tricore-as16/ZombiFPS pull request #21
Opened 2024-08-20 06:31 UTC by tricore-as16

銃
・発砲音
・空うち音
・敵に当たった音
・外れた音
・リロード音

プレイヤー
・歩く音
・走る音

エネミー
・ゾンビの叫び声

システム
・お金を支払った時の音
・シャッターが開く音

などを追加しました。

2024-08-28 06:06 UTC, tricore-as07 commented
前にも一度指摘しましたが、画像や音源ファイルなどのアセットの追加量が多い場合は
スクリプトの変更と別でPR作ってもらえると助かります

2024-08-28 06:15 UTC, tricore-as07 requested changes

2024-08-28 06:15 UTC, tricore-as07 commented on Enemy.cpp
> +        //soundManager->PlaySoundListSE(SoundManager::EnemyHitSE);
[Q]
これは使わなくなったコードですかね？

2024-08-28 06:15 UTC, tricore-as07 commented on EnemyGroupController.cpp
> +            soundManager->PlaySoundListSE(SoundManager::ZombieVoice1SE);
[MUST]
こういう複数行ある処理をインデントだけして{}で囲んでいないものはコーディングルール違反です

2024-08-28 06:15 UTC, tricore-as07 commented on GameScene.cpp
> +    // お金を払った時の音
[MUST]
コメントの位置が不適切な気がします

2024-08-28 06:15 UTC, tricore-as07 commented on Player.h
> +    bool                    isShooting;                 // 発砲状態か
[Q]
このあたりの状態管理が複数のboolやenumで分かれているのは何か理由があるのでしょうか？

2024-08-28 06:15 UTC, tricore-as07 commented on SoundManager.cpp
> +    int playerDamageSE              = LoadSoundMem("");
[Q]
これ何も入力されていないですが大丈夫ですかね？

2024-08-28 06:15 UTC, tricore-as07 commented on SoundManager.h
> +        WalkingBGM,              // 歩く音
[Q]
歩く音や走る音はBGMではない気がしますが何か意図があってBGMにしていますか？

2024-08-30 08:11 UTC, tricore-as16 commented on Enemy.cpp
> +        //soundManager->PlaySoundListSE(SoundManager::EnemyHitSE);
申し訳ありません。
この段階のブランチだと当たり判定がうまく処理できておらず、数回連続で音声が再生されてしまっていたためその不具合を修正してからコメントアウトを外そうと思い、コメントアウトしている状態です。

2024-08-30 08:12 UTC, tricore-as16 commented on EnemyGroupController.cpp
> +            soundManager->PlaySoundListSE(SoundManager::ZombieVoice1SE);
申し訳ありません。
一旦このプルリクエスト内のswich分のみ変更します。
swich()
{
     case 0:
     {
               soundManager->....
      }
}

のような修正でよいという認識でよろしかったでしょうか？

2024-08-30 08:15 UTC, tricore-as16 commented on GameScene.cpp
> +    // お金を払った時の音
申し訳ありません。
コメント変更しました。

2024-09-02 01:52 UTC, tricore-as16 commented on SoundManager.cpp
> +    int playerDamageSE              = LoadSoundMem("");
今現在は実装済みなのですが、この段階では必要最小限の音のみ入れたのでのちのブランチで実装してしまったため、このままでもよろしいでしょうか？

2024-09-02 01:57 UTC, tricore-as16 commented on SoundManager.h
> +        WalkingBGM,              // 歩く音
バックグラウンド再生するものをSE、ループ再生するものをBGMとしたのですが、
歩いている間歩き音を再生してほしいところを歩きの音の再生時間が11秒ほどと長く、再生終了した後にループ再生しないと音が重なってしまうためBGMとしました。

2024-09-02 02:19 UTC, tricore-as16 commented on Player.h
> +    bool                    isShooting;                 // 発砲状態か
インタラクト関連のisInteractedを作成したのはシャッターや武器強化マシンにプレイヤーからのアクセスがあることをゲッターで伝えるために作成しました。
enumで定義したInteractLocationStateはどのオブジェクトに現在インタラクトできるかどうかの状態で、この変数をbool型の代わりとしてif|(interactLocationState != None)みたいに使用することも考えたのですが、CollisionData構造体にプレイヤーしか使用しないenumを入れるのは変かと思い、シャッターや武器強化マシンに共通するbool型をOnHitで伝達する様で作成しました。

2024-09-02 02:29 UTC, tricore-as16 commented on EnemyGroupController.cpp
> +            soundManager->PlaySoundListSE(SoundManager::ZombieVoice1SE);
すいません。うまく改行されないため改めて送信します。

2024-09-02 03:40 UTC, tr-k-orimoto commented on Enemy.cpp
> +        //soundManager->PlaySoundListSE(SoundManager::EnemyHitSE);
であればその旨をFIXMEなどで記載したほうがいいですね

2024-09-02 03:40 UTC, tr-k-orimoto commented on EnemyGroupController.cpp
> +            soundManager->PlaySoundListSE(SoundManager::ZombieVoice1SE);
このPRの変更差分内のみの対応で問題ないです
認識も間違ってないです

2024-09-02 03:40 UTC, tr-k-orimoto commented on Player.h
> +    bool                    isShooting;                 // 発砲状態か
state、isShooting、reloadStateなどに関することを聞いていたので
ちょっと説明されている内容がずれてる気がします

2024-09-02 03:40 UTC, tr-k-orimoto commented on SoundManager.cpp
> +    int playerDamageSE              = LoadSoundMem("");
その場合はTODOコメントなどを適切に使った方がいいですね

2024-09-02 04:22 UTC, tricore-as16 commented on Enemy.cpp
> +        //soundManager->PlaySoundListSE(SoundManager::EnemyHitSE);
承知しました。
FIXMEコメント追加しました。

2024-09-02 04:27 UTC, tricore-as16 commented on SoundManager.cpp
> +    int playerDamageSE              = LoadSoundMem("");
承知しました。
TODOコメント追加しました。

2024-09-02 04:29 UTC, tricore-as16 commented on SoundManager.h
> +        WalkingBGM,              // 歩く音
DXライブラリのPlaySoundMem関数の引数指定でDX_PLAYTYPE_BACKを使用するものはSoundEffectType、
DX_PLAYTYPE_LOOPを使用するものはLoopSoundTypeに命名変更しました。

2024-09-02 04:34 UTC, tricore-as16 commented on Player.h
> +    bool                    isShooting;                 // 発砲状態か
申し訳ありません。

stateでプレイヤーの状態を定義しているのですが、isShootingの射撃状態ではstateで定義するとほかの状態とかぶる可能性があるため(歩きながら撃つなど)ほかの変数にしました。

reloadStateはリロード音を実装する時にリロード開始時と終了時に音を再生したかったため、細かい状態を管理する必要があったためenumとしました。

2024-09-02 04:50 UTC, tricore-as16 commented on EnemyGroupController.cpp
> +            soundManager->PlaySoundListSE(SoundManager::ZombieVoice1SE);
このプルリク変更差分のみ一旦修正しました。

2024-09-02 04:58 UTC, tr-k-orimoto requested changes
LGTM

2024-09-02 04:58 UTC, tr-k-orimoto approved these changes

2024-09-03 01:08 UTC, merged