エフェクトを追加しました。
tricore-as16/ZombiFPS pull request #22
Opened 2024-08-20 06:32 UTC by tricore-as16

・銃の発砲時のマズルフラッシュエフェクト
・敵に着弾した時の、血しぶきエフェクト

を追加しました。

2024-08-30 09:40 UTC, tricore-as03 commented
https://github.com/tricore-as16/ZombiFPS/pull/18
以前のプルリクの対応部分が混ざってるみたいですが、マージ先のブランチの指定とかが間違ってませんか？

2024-08-30 09:42 UTC, tricore-as03 requested changes
https://github.com/tricore-as16/ZombiFPS/pull/18
以前のプルリクの対応部分が混ざってるみたいですが、マージ先のブランチの指定とかが間違ってませんか？

2024-09-03 01:13 UTC, tricore-as16 commented
申し訳ありません。前のブランチの内容を反映させましたので確認お願いしてもよろしいでしょうか？

2024-09-03 01:17 UTC, tricore-as16 commented
申し訳ありません。今思い出したのですが、このブランチ作業中に学校で作業しており弾丸の当たり判定が１回行うところを複数回行ってしまっていた不具合の解決方法をその場で先生に質問してしまい、このブランチ内でその対応を行ってしまっていました。申し訳ありません。

2024-09-03 01:52 UTC, tricore-as03 approved these changes
LGTM

2024-09-03 02:09 UTC, merged