タイトルシーンを追加
tricore-as16/ZombiFPS pull request #23
Opened 2024-08-20 06:34 UTC by tricore-as16

・タイトルシーンを追加しました
・ステージ、エネミー、カメラを実装
・監視カメラでエネミーを監視しているような演出を行いました

2024-08-30 09:45 UTC, tricore-as03 requested changes
このプルリクも前の対応部分が混ざってるので確認してください。

2024-09-03 01:20 UTC, tricore-as16 commented
前のブランチの内容を反映しました。
ご確認お願いしてもよろしいでしょうか？

2024-09-03 01:49 UTC, tricore-as03 approved these changes
LGTM

2024-09-03 01:49 UTC, tricore-as03 commented on Pathfinding.cpp
> +    initRoomData[West1]     = { West1,     West1RoomCenterPosition  ,      30,        40,       imageDataManager->GetImageHandle(ImageDataManager::West1ImageData) };
[IMO]
必須ではないですが、部屋ごとのデータクラスを作成して、for文で一括で設定するとよいですね。

2024-09-03 02:17 UTC, tricore-as16 commented on Pathfinding.cpp
> +    initRoomData[West1]     = { West1,     West1RoomCenterPosition  ,      30,        40,       imageDataManager->GetImageHandle(ImageDataManager::West1ImageData) };
ありがとうございます！試させていただきたいと思います。

2024-09-03 02:22 UTC, merged