プレイヤーを実装しました
tricore-as16/ZombiFPS pull request #4
Opened 2024-07-23 08:18 UTC by tricore-as16

・プレイヤー専用のカメラを用意しFPS視点にしました
・プレイヤーモデルとプレイヤー専用カメラの動きを合わせました(回転を同期)
・マウス操作に対応させました
・移動キーをWASDに変更しました
・マウス入力していなくてもカメラが少しづつ上に移動してしまっていたため、入力のデッドゾーンを設けました

モデルのスケールをVGet( 1, 1, 1);にした方がよい件ですが、カメラのニアファーの関係上できるだけモデルを小さくしたかったのでステージのスケールを分かりやすく小さくできるのがプログラム上でしかできなかったためMV1SetScaleでスケール調整してしましました。

2024-07-23 08:31 UTC, tricore-as07 requested changes

2024-07-23 08:31 UTC, tricore-as07 commented on Player.cpp
> +bool Player::UpdateMoveParameterWithPad(const Input& input, const PlayerCamera& playerCamera,
[MUST]
ここの関数名と返り値などの意味が伝わらない点を口頭で指摘してたと思うので修正をお願いします

2024-07-23 08:31 UTC, tricore-as07 commented on Player.cpp
> +    VECTOR OldPos = position;                           // �ړ��O�̍��W
[MUST]
命名規則違反

2024-07-23 08:31 UTC, tricore-as07 commented on GameScene.cpp
> +    playerCamera->Update(*input, *player,*stage);       // �v���C���[�J�����̍X�V
[MUST]
PlayerCameraとPlayerが相互依存関係になっているので、
PlayerがPlayerCameraを持つように修正をお願いします。

2024-07-23 09:07 UTC, tricore-as07 requested changes

2024-07-23 09:07 UTC, tr-k-orimoto commented on ImageDataManager.h
> +    static map<ImageDataType, int>  imageDataList;      // �g�p����摜�̃f�[�^���X�g
[MUST]
ここはstaticを外すようにお願いします

2024-07-23 09:07 UTC, tr-k-orimoto commented on Input.cpp
> +
[MUST]
無駄に差分が増えてしまうのであまり不要な改行を増やさないようにお願いします。

2024-07-23 09:07 UTC, tr-k-orimoto commented on ModelDataManager.cpp
> +    modelDataList[StageModelData] = MV1LoadModel("Data/Stage/backroomsScaleMini.mv1");
特に決まりはないですが、ファイル名は基本的にアッパーキャメルが多いかなと思います

2024-07-23 09:07 UTC, tr-k-orimoto commented on Player.cpp
> +    shadowHandle = LoadGraph("Shadow.tga");
[Q]
これはImageDataManagerでまとめないんでしょうか？

2024-07-23 09:07 UTC, tr-k-orimoto commented on Player.cpp
> +    // TODO: �}�W�b�N�i���o�[��4�����Ȃ̂���͂��Ē萔��
[Q]
ここのTODOコメントはまだ必要でしょうか？

2024-07-23 09:07 UTC, tr-k-orimoto commented on Player.cpp
> +    VECTOR	UpMoveVec;		// �����{�^���u���v����͂������Ƃ��̃v���C���[�̈ړ������x�N�g��
[MUST]
命名規則違反

2024-07-23 09:07 UTC, tr-k-orimoto commented on Player.h
> +    float       angle;                  // ���f���������Ă�������̊p�x
[MUST]
方向ベクトルと方向の角度は意味が重複しているのでどちらかの変数名とコメントの修正をお願いします

2024-07-23 09:07 UTC, tr-k-orimoto commented on Player.h
>      bool        isMove;                 // ���̃t���[���œ��������ǂ���
[MUST]
こちらも口頭で指摘したとおり命名の修正をお願いします

2024-07-23 09:07 UTC, tr-k-orimoto commented on PlayerCamera.cpp
> +        float NotHitLength;
[MUST]
命名規則違反

2024-07-24 00:32 UTC, tricore-as16 commented on Player.cpp
> +    VECTOR OldPos = position;                           // �ړ��O�̍��W
すいません。修正しました。

2024-07-24 00:35 UTC, tricore-as16 commented on ImageDataManager.h
> +    static map<ImageDataType, int>  imageDataList;      // �g�p����摜�̃f�[�^���X�g
承知しました。ModelLoadManagerと同様にstaticはずしました。

2024-07-24 00:35 UTC, tricore-as16 commented on Input.cpp
> +
すいません。承知しました。

2024-07-24 00:37 UTC, tricore-as16 commented on Player.cpp
> +    shadowHandle = LoadGraph("Shadow.tga");
影は描画しないので削除しました。

2024-07-24 00:39 UTC, tricore-as16 commented on Player.cpp
> +    // TODO: �}�W�b�N�i���o�[��4�����Ȃ̂���͂��Ē萔��
不要なので削除しました。

2024-07-24 00:39 UTC, tricore-as16 commented on Player.cpp
> +    VECTOR	UpMoveVec;		// �����{�^���u���v����͂������Ƃ��̃v���C���[�̈ړ������x�N�g��
すいません。修正しました。

2024-07-24 00:40 UTC, tricore-as16 commented on Player.h
>      bool        isMove;                 // ���̃t���[���œ��������ǂ���
isMove　→　currentFrameMove　に変更しました。

2024-07-24 00:44 UTC, tricore-as16 commented on PlayerCamera.cpp
> +        float NotHitLength;
すいません。修正しました。

2024-07-24 00:46 UTC, tricore-as16 commented on ModelDataManager.cpp
> +    modelDataList[StageModelData] = MV1LoadModel("Data/Stage/backroomsScaleMini.mv1");
承知しました。アッパーキャメルに変更しました。

2024-07-24 01:15 UTC, tricore-as16 commented on Player.cpp
> +bool Player::UpdateMoveParameterWithPad(const Input& input, const PlayerCamera& playerCamera,
内容的に当たり判定を行っていない場合の「移動ベクトルを更新」しているのでUpdateMoveVectorに変更しました。
返り値はなくして、新たに移動ボタンが押されたかの変数pressMoveButtonを宣下し、そこに返り値だったデータを格納しました。

2024-07-24 01:17 UTC, tr-y-saitu commented on Player.h
> +    float       angle;                  // ���f���������Ă�������̊p�x
float angle;　の方を使用していなかったため削除しました。

2024-07-24 01:50 UTC, tricore-as16 commented on GameScene.cpp
> +    playerCamera->Update(*input, *player,*stage);       // �v���C���[�J�����̍X�V
承知しました。PlyaerがPlayerCameraを持つように修正しました。

2024-07-24 02:05 UTC, tricore-as07 commented on Player.cpp
> +    VECTOR OldPos = position;                           // �ړ��O�̍��W
まだほかにも命名規則違反があるので
一回指摘された内容は一度すべてのコードを自分で確認するようにしましょう

2024-07-24 02:47 UTC, tricore-as16 commented on Player.cpp
> +    VECTOR OldPos = position;                           // �ړ��O�̍��W
すいません。
一度すべて確認して修正しました。

2024-07-24 03:21 UTC, tricore-as07 approved these changes
LGTM

2024-07-24 04:04 UTC, merged