銃の弾丸を作成
tricore-as16/ZombiFPS pull request #7
Opened 2024-07-26 03:05 UTC by tricore-as16

・弾丸のオブジェクトプールを作成
・オブジェクトプールから未使用弾丸を、銃クラスに渡して更新できるように修正
・マウス左クリックで射撃を追加

弾丸はモデルを持っていないは仕様です
カメラのターゲット視点に進むベクトルとで線を作り、エネミー当たり判定の球型との線と球の当たり判定を行い当たっていたら球を消すという処理を今後追加したいと思います。

2024-07-26 04:18 UTC, tricore-as03 requested changes

2024-07-26 04:18 UTC, tr-t-mitsumaru commented on BulletObjectPools.cpp
> +bool BulletObjectPools::hasInactiveBulletInstance()
[MUST]
関数名が先頭小文字になってます。

2024-07-26 04:18 UTC, tricore-as03 commented on BulletObjectPools.cpp
> +void BulletObjectPools::AcquireInactiveBulletInstance(list<Bullet*>& activeBullet, Bullet::BulletInitializeData initializeData)
[MUST]
関数名を`GetBullet`とかにして、未使用の弾丸を戻り値で返すような流れで良いかと。
activeBulletへの追加は、この関数で呼びだし元で行ってしまって良いかと。

2024-07-26 05:42 UTC, tricore-as16 commented on BulletObjectPools.cpp
> +bool BulletObjectPools::hasInactiveBulletInstance()
すいません。確認不足でした。修正しました。

2024-07-26 06:57 UTC, tricore-as16 commented on BulletObjectPools.cpp
> +void BulletObjectPools::AcquireInactiveBulletInstance(list<Bullet*>& activeBullet, Bullet::BulletInitializeData initializeData)
質問なのですが、
インスタンスの移動を list 関数の splice で未使用の要素を使用中に移動。という処理だったのが、

spliceを使わずに front , pop_ front   とpush_backを使用して要素移動するということでしょうか？

list<Bullet*> GetBullet()

// 未使用のインスタンスがあるかチェック
if()
{
    // 未使用のプールの先頭から要素を取得
　Bullet *   bullet  =  inactiveBullet . front () ;

   // 移動させるので先頭要素を削除
   icactiveBullet . pop_front () ;

   return  bullet;   
}

}
else
{
 retrun   nullptr ;
}


//  呼び出し側
void Payer UpdateShooting....
{
    //  弾丸の初期化データを取得
   Bullet :: BulletInitializeData   initData = equippedGun->GetBulletInitializeData() ;

   // 未使用の弾丸を取得
   Bullet*  bullet   = bulletObejctPools -> GetBullet() ;

   // 取得した弾丸があるなら使用中に追加
   if(bullet  != nullptr )
  {
      equippedGun -> GetActiveBullet() . pushu_back(bullet ) ; 
  }

}

みたいになるという認識でよかったでしょうか？

2024-07-29 06:30 UTC, tricore-as03 requested changes

2024-07-29 06:30 UTC, tr-t-mitsumaru commented on BulletObjectPools.cpp
> +void BulletObjectPools::AcquireInactiveBulletInstance(list<Bullet*>& activeBullet, Bullet::BulletInitializeData initializeData)
はい、その認識であってます。

2024-07-29 06:30 UTC, tricore-as03 commented on Player.cpp
> +        Bullet::BulletInitializeData initData = equippedGun->GetBulletInitializeData();
[MUST]
不要であれば消してください。

2024-07-29 06:36 UTC, tricore-as16 commented on Player.cpp
> +        Bullet::BulletInitializeData initData = equippedGun->GetBulletInitializeData();
すいません。弾丸を初期化していなかったので初期化しました。

2024-07-29 06:38 UTC, tricore-as03 approved these changes
LGTM

2024-07-29 06:39 UTC, merged